# Author: Mario Guriuc

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html/
    networks:
      - mongoNetwork
    depends_on:
      - mongo-dead

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8001:8001"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  mongo-dead:
    image: mongo:7.0.2
    ports:
      - "27018:27017"
    networks:
      - mongoNetwork

  mongo-script:
    image: python:3.9
    build:
      context: .
      dockerfile: Dockerfile-mongo
    volumes:
      - ./Database:/Database
    networks:
      - mongoNetwork
    depends_on:
      - mongo-dead
    command: python /Database/db_script.py


networks:
  mongoNetwork:
    driver: bridge
