# Author: Mario Guriuc

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html/
    networks:
      - mongoNetwork
    depends_on:
      - mongo-dead

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8001:80"
    volumes:
      - ./frontend:/var/www/html/
    depends_on:
      - backend

  mongo-dead:
    image: mongo:7.0.2
    ports:
      - "27018:27017"
    networks:
      - mongoNetwork

networks:
  mongoNetwork:
    driver: bridge
