# Author: Mario Guriuc

services:
  centers-service:
    build:
      context: .
      dockerfile: Dockerfile-backend-centers
    ports:
      - "8001:80"
    volumes:
      - ./backend/centers_service:/var/www/html/
    networks:
      - mongoNetwork
    depends_on:
      - mongo-dead

  users-service:
    build:
      context: .
      dockerfile: Dockerfile-backend-users
    ports:
      - "8002:80"
    volumes:
      - ./backend/users_service:/var/www/html/
    networks:
      - mongoNetwork
    depends_on:
      - mongo-dead

  inmates-service:
    build:
      context: .
      dockerfile: Dockerfile-backend-inmates
    ports:
      - "8003:80"
    volumes:
      - ./backend/inmates_service:/var/www/html/
    networks:
      - mongoNetwork
    depends_on:
      - mongo-dead

  visits-service:
    build:
      context: .
      dockerfile: Dockerfile-backend-visits
    ports:
      - "8004:80"
    volumes:
      - ./backend/visits_service:/var/www/html/
    networks:
      - mongoNetwork
    depends_on:
      - mongo-dead

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - centers-service
      - users-service
      - inmates-service
      - visits-service

  mongo-dead:
    image: mongo:7.0.2
    ports:
      - "27018:27017"
    networks:
      - mongoNetwork

  mongo-script:
    image: python:3.9
    build:
      context: .
      dockerfile: Dockerfile-mongo
    volumes:
      - ./Database:/Database
    networks:
      - mongoNetwork
    depends_on:
      - mongo-dead
    command: python /Database/db_script.py


networks:
  mongoNetwork:
    driver: bridge
